spring.application.name=IATestPreparator

# Database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

server.port=${PORT:8080}

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000

# File sizes
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# File directory
upload.path=/app/uploads

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Http incoming requests Timeout
server.tomcat.connection-timeout=300000
# Client HTTP request TimeOut for Ollama
